title: blog.mtib.dev
author: Markus Becker
email: mtib.becker@gmail.com
url: https://blog.mtib.dev
favicon: "./m_arrow.png" 
description: > # description of the site (multiple lines allowed)
    Starting to write a blog is hard, but here's a try.
theme: no-style-please
theme_config:
  appearance: "auto" # can be "light", "dark" or "auto"
  back_home_text: ".." # customize text for homepage link in post layout
  date_format: "%Y-%m-%d" # customize how date is formatted
  show_description: false # show blog description in home page
permalink: /:slug.html

sass:
  style: :compressed

plugins:
  - jekyll-feed
  - jekyll-seo-tag
